version: "3"
volumes:
  # MySQL Data
  admin-policlinica-data:
    driver: local

services:
  mysql:
    image: mysql
    container_name: admin-policlinica-mysql
    volumes:
      - admin-policlinica-data:/var/lib/mysql
    ports:
      - "3366:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=policlinicadb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  web:
    image: roinuj16/php7.1
    container_name: admin-policlinica
    ports:
      - "8000:80"
      - "81:80"
    links:
      - mysql
    volumes:
      - ../.:/var/www/app
      - ./config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf